# Generated by Django 4.2.5 on 2024-02-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=20)),
                ('crypto_gr_key', models.CharField(max_length=50)),
            ],
        ),
    ]
