# Generated by Django 5.0.1 on 2024-01-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diepvries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot_nummer', models.IntegerField()),
                ('omschrijving', models.CharField(max_length=50)),
                ('personen', models.IntegerField()),
                ('datum', models.DateField(auto_now=True)),
            ],
        ),
    ]
