# Generated by Django 5.0.1 on 2024-01-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_diepvries_pot_nummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diepvries',
            name='personen',
            field=models.CharField(max_length=2),
        ),
    ]
